version: 1
product:
  id: prod-ghostlink
  name: GhostLink
  owner: product-owner
  vision: A zero-infrastructure, browser-based secure messaging tool that ensures
    total privacy by storing data nowhere but the user's device.
  constraints:
  - No backend servers or databases
  - Static hosting only (Cloudflare Pages)
  - Zero maintenance cost
  - Data exists only in RAM or URL fragment
  - No user accounts or login
  rules:
  - All encryption must happen client-side via Web Crypto API
  - Keys must never be sent over the network (except inside URL fragment hash)
  - WebRTC signaling must be manual (Copy/Paste SDP) to avoid signaling servers
  - 'Impossible: Push notifications (requires APNS/FCM server)'
  - 'Impossible: Offline message queuing (requires DB)'
  - 'Impossible: User directory (requires DB)'
  requirements:
  - AES-GCM 256-bit encryption
  - URL-based message transport (max ~2KB payload)
  - Ephemeral UI - clear history on load
  - Responsive design for mobile/desktop
  status: active
