version: 1
product:
  id: prod-001
  name: GhostLink
  owner: product-owner
  vision: A zero-infrastructure, end-to-end encrypted messaging web app providing
    secure, ephemeral communication without backend servers or persistent storage.
  constraints:
  - Zero Backend
  - Static Hosting Only
  - No Persistent Data
  - Client-Side Only
  rules:
  - All encryption must happen client-side using Web Crypto API.
  - No data is sent to any server; URL hash fragments are used for transport.
  - 'Impossible features: Push notifications, offline message buffering, user lookup/directory.'
  - Real-time chat requires manual SDP exchange (no signaling server).
  requirements:
  - AES-GCM 256-bit encryption
  - WebRTC Data Channels
  - Responsive Mobile/Desktop UI
  status: active
